services:
  - type: web
    name: firex-attendance
    runtime: node
    plan: free
    region: frankfurt # or oregon / singapore / ohio
    buildCommand: npm install && npm run build
    startCommand: node server/index.js
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: TIMEZONE
        value: Asia/Bahrain
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
